# plugin.yml
name: DualHandGlow
version: 1.0
main: com.nonkungch.dualhandglow.DualHandGlow
api-version: 1.21 # รองรับ 1.21+
author: NonKungCH
# softdepend: [ProtocolLib] ถูกลบออกแล้ว

commands:
  offhand:
    description: Swaps the item in your main hand and off hand.
    usage: /<command>
    aliases: [ofh]
    permission: dualhandglow.swap
    permission-message: You do not have permission to use this command.
