# plugin.yml
name: DualHandGlow
version: 1.0
# อัปเดต Main Class ให้ชี้ไปที่คลาสที่เปลี่ยนชื่อใหม่
main: com.nonkunghc.offhandlight.DualHandGlow 
api-version: 1.21
author: NonKungCH

commands:
  offhand:
    description: Swaps the item in your main hand and off hand.
    usage: /<command>
    # เพิ่ม alias /ofh
    aliases: [ofh] 
    permission: dualhandglow.swap # อัปเดต permission
    permission-message: You do not have permission to use this command.
