# plugin.yml
name: DualHandGlow
version: 1.0
main: com.nonkungch.dualhandglow.DualHandGlow
api-version: 1.21
author: NonKungCH
softdepend: [LightAPI] # ระบุว่าปลั๊กอินนี้ใช้ LightAPI แต่ไม่จำเป็นต้องมี
# ... (Commands เหมือนเดิม) ...

commands:
  offhand:
    description: Swaps the item in your main hand and off hand.
    usage: /<command>
    aliases: [ofh]
    permission: dualhandglow.swap
    permission-message: You do not have permission to use this command.
